spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eficio
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:eficio_secret_key_2024_secure_and_very_long_key_for_development}
  expiration: 86400000 # 24 horas em milissegundos

logging:
  level:
    org.springframework.security: DEBUG
    com.eficio.backend: DEBUG 